# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a9a1849a0d5eb5760da1edc122f118f031c04f1378d46456f1c56229c3a3b0b21dac0b63d918da926b2c9b1b8547e8ea89a4fc7ae0021b570bd43293157de01

test:
  secret_key_base: 4a1548b72f312cf24dd7a12e255e4228f26614841c714e66b03f097f12060b542ca87d2343154ad88142c0047b3c0e8d5e35456c8bb70b35194bbbdf126dbe5d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
